configfile: "config/config.yml"
conda: "envs/main.yml"

include: "rules/setup.smk"
include: "rules/input.smk"
include: "rules/trim.smk"
include: "rules/fastqc.smk"
include: "rules/align.smk"
include: "rules/utils.smk"
include: "rules/mark_duplicates.smk"
include: "rules/peak_calling.smk"
include: "rules/data_analysis.smk"

rule all:
    input:
        get_all_input(RESULTS, pipeline_config)
    default_target: True
    params:
        temp_path = config["temp_path"]
    shell:
        "rm -rf {params.temp_path}"
