import sys
sys.path.append("workflow/scripts")
from sampleFileScripts import getAllSampleFilePaths


configfile: "config/config.yml"

include: "rules/fastqc.smk"
include: "rules/align.smk"

module downloadWorkflow:
    snakefile: "rules/download.smk"
    config: config["downloadWorkflow"]


module trimWorkflow:
    snakefile: "rules/trim.smk"
    config: config["trimmingWorkflow"]

module alignmentWorkflow:
    snakefile: "rules/align.smk"
    config: config["alignmentWorkflow"]


use rule * from downloadWorkflow
use rule * from trimWorkflow as trim_*
use rule * from alignmentWorkflow as align_*



rule downloadAllSamples:
    input:
        *getAllSampleFilePaths()

trimmer = config["workflow"]["trimmer"]
rule trim:
    input:
        list(map(lambda fileName: f"results/{trimmer}/{fileName}", getAllSampleFilePaths(includeDirectories=False)))

rule align:
    input:
        
