downloadWorkflow:
  fasterq-dump:
    downloadPath: "resources/reads"
    args: ""

trimmingWorkflow:
  trimgalore:
    inputPath: "resources/reads"
    args: ""

  cutadapt:
    args: ""

  fastp:
    args: ""

bowtie2:
  args: ""

alignmentWorkflow:
  bowtie2:
    args: ""

trimmer: "trim_galore"
fastp_options: ""
trim_galore_options: ""


aligner: "bowtie2"
bowtie2_options: ""
libraryStrategy: "paired"
providedFileExtension: "fastq"

genome: "mm39"

path_to_reads: ""

samtools: "-f 4"

modules: ""