downloadWorkflow:
  fasterq-dump:
    downloadPath: "resources/reads"
    args: ""

trimmingWorkflow:
  trimgalore:
    inputPath: "resources/reads"
    args: ""

  cutadapt:
    args: ""

  fastp:
    args: ""

alignmentWorkflow:
  trimmer: "trimgalore"
  genome: "mm39"
  bowtie2:
    args: ""

workflow:
  trimmer: "cutadapt"
  aligner: "bowtie2"