# Workflow config
indexing_threads: 12
aligning_threads: 12



# String to overwrite which tools are to be run
modules: ""
# Choose trimmer
trimmer: "trim_galore"
# Choose alginer
aligner: "bowtie2"
# Choose tool to process duplicates
duplicate_processor: "markdup"
peak_caller: "macs3"

# Genome to be used to peak call and align
genome: "mm10"

generate_fastqc_reports: True

# Plotting region for peaks plotted by pyGenomeTracks
plot_regions: "chr1:14,000,000-15,000,000"

# Defined reads in sample sheet are paired end
paired_end: True

# Path to sample sheet
sample_sheet: "config/samples.csv"

# Path to write generated files to
outdir: ""
json_path: "samples.json"
results_path: "results"
resources_path: "resources"
logs_path: "logs"
benchmarks_path: "benchmarks"
temp_path: "temp"

# Times chosen trimmer is repeated for chosen trimmer
benchmark_repeat_trim: 1
# Times chosen aligner is repeated for chosen aligner
benchmark_repeat_align: 1
# Times chosen duplicate marker is repeated for chosen duplicate processor
benchmark_repeat_duplicate: 1


fasterq-dump:
  downloadPath: "resources/reads"
  args: ""

fastqc:
  args: ""
  threads: 12
  mem_mb: 4000

# Trimmer config
trim_threads: 12

trim_galore:
  threads: 12
  args: ""
cutadapt:
  threads: 12
  args: ""
fastp:
  threads: 12
  args: ""
trimmomatic:
  threads: 12
  args: ""
  run_options: "ILLUMINACLIP:TruSeq3-PE.fa:2:30:10:2:True LEADING:3 TRAILING:3 MINLEN:36"

# Aligner config


bowtie2:
  args: "--very-sensitive"
bowtie2-build:
  args: ""
bwa-mem:
  args: "-v 1 -Y"
bwa-mem2:
  args: "-v 1 -Y"
bwa-index:
  args: ""
star:
  args: ""

# Utils config
gzip:
  args: ""
samtools-index:
  threads: 4
MarkDuplicates:
  args: ""
markdup:
  args: "-s"
  threads: 12

# Peak calling config
macs3:
  args: ""
pyGenomeTracks:
  args: ""
  # Comma seperated options will be appended the track files
  bigwig_options: "max_value = 6"
  bed_options: ""

# Deeptools computeMatrix args used for plot_heat_map and plot_profile
computeMatrix:
  threads: 12
  args: "--referencePoint 'center' --skipZeros -a 4000 -b 4000"

homer:
  threads: 12
  args: "-size 200"
