fasterq-dump:
  downloadPath: "resources/reads"
  args: ""

# Trimmer config
trimgalore:
  args: ""
cutadapt:
  args: "--quiet"
fastp:
  args: ""

# Aligner config
bowtie2:
  args: "--quiet --very-fast"
  extra: ""
bowtie2-build:
  args: "--quiet"
bwa:
  args: "-v 1 -Y"
  extra: ""
bwa-index:
  args: ""
STAR:
  extra: ""
  threads: 8
  args: ""

# Utils config
MarkDuplicates:
  args: "--REMOVE_SEQUENCING_DUPLICATES true"
markdup:
  args: ""

# Peak calling config
macs3:
  args: "--nomodel -g hs --bdg"

computeMatrix:
  args: "--referencePoint 'center' --skipZeros -a 4000 -b 4000"

# Workflow config
modules: ""
trimmer: "trim_galore"
aligner: "bowtie2"
duplicate_processor: "samtools-markdup"
peak_caller: "macs3"
genome: "mm39"
paired_end: True
samtools: "-f 4"
