fasterq-dump:
  downloadPath: "resources/reads"
  args: ""

# Trimmer config
trimgalore:
  args: ""
cutadapt:
  args: ""
fastp:
  args: ""
trimmer: "trim_galore"

# Aligner config
bowtie2:
  args: ""
  extra: ""
bowtie2-build:
  args: ""
bwa:
  args: "-Y"
  extra: ""
bwa-index:
  args: ""
STAR:
  extra: ""
  threads: 8
  args: ""

# Peak calling config
macs3:
  args: "--broad"

# Workflow config
modules: ""
duplicate: "picard-MarkDuplicates"
aligner: "bowtie2"
genome: "mm39"
paired_end: true
samtools: "-f 4"
