downloadWorkflow:
  fasterq-dump:
    downloadPath: "resources/reads"
    args: ""

trimmingWorkflow:
  trimgalore:
    inputPath: "resources/reads"
    args: ""

  cutadapt:
    args: ""

  fastp:
    args: ""

alignmentWorkflow:
  trimmer: trimmer 
  genome: "mm10"
  bowtie2:
    args: ""

path_to_reads: "results/reads"
trimmer: "trim_galore"
aligner: "bowtie2"
genome: "mm10"
bowtie2:
  args: ""
