fasterq-dump:
  downloadPath: "resources/reads"
  args: ""


# Trimmer config
trimgalore:
  args: ""
cutadapt:
  args: ""
fastp:
  args: ""
trimmer: "trim_galore"

bowtie2:
  args: ""
  extra: ""
bowtie2-build:
  args: ""
bwa:
  args: "-Y"
  extra: ""
bwa-index:
  args: ""
STAR:
  extra: ""
  threads: 8
  args: ""

macs3:
  args: ""

aligner: "bowtie2"
bowtie2_options: ""
paired_end: true 
providedFileExtension: "fastq"
genome: "mm39"
modules: ""
samtools: "-f 4"