fasterq-dump:
  downloadPath: "resources/reads"
  args: ""

# Trimmer config
trimgalore:
  args: ""
cutadapt:
  args: "--quiet"
fastp:
  args: ""

# Aligner config
bowtie2:
  args: "--quiet"
  extra: ""
bowtie2-build:
  args: "--quiet"
bwa:
  args: "-v 1 -Y"
  extra: ""
bwa-index:
  args: ""
STAR:
  extra: ""
  threads: 8
  args: ""

MarkDuplicates:
  args: "--REMOVE_SEQUENCING_DUPLICATES true"

# Peak calling config
macs3:
  args: ""

# Workflow config
modules: ""
trimmer: "trim_galore"
aligner: "bowtie2"
duplicate_processor: "picard-MarkDuplicates"
genome: "mm39"
paired_end: true
samtools: "-f 4"
