downloadWorkflow:
  fasterq-dump:
    downloadPath: "resources/reads"
    args: ""

trimmingWorkflow:
  trimgalore:
    inputPath: "resources/reads"
    args: ""

  cutadapt:
    args: ""

  fastp:
    args: ""

alignment:
  trimmer: "trimgalore"

workflow:
  trimmer: "cutadapt"
  aligner: "bowtie2"