fasterq-dump:
  downloadPath: "resources/reads"
  args: ""


# Trimmer config
trimgalore:
  inputPath: "resources/reads"
  args: ""

cutadapt:
  args: ""

fastp:
  args: ""



trimmer: "trim_galore"
fastp_options: ""
trim_galore_options: ""

bowtie2:
  args: ""
bowtie2-build:
  args: ""
bwa:
  args: ""
bwa-index:
  args: ""
STAR:
  threads: 8
  args: ""


aligner: "bowtie2"
bowtie2_options: ""
libraryStrategy: "paired"
providedFileExtension: "fastq"

genome: "mm39"

path_to_reads: ""

samtools: "-f 4"

modules: ""