executor: slurm
latency-wait: 60
conda-frontend: conda
use-conda: True
rerun-incomplete: True
retries: 3

default-resources:
  slurm_account: "Insert account here"
  slurm_partition: "Insert partition here"
  runtime: 120
  mem_mb: 512
  cpus_per_task: 1
